version: "3.8"

services:
  web:
    container_name: us_sesion
    build: ./
    ports:
      - "4001:4001"
    environment:
      DD_DB_HOST: db
    #command: /server
    depends_on:
      - db
  db:
    container_name: us_sesion_db
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
networks:
    default:
        external:
            name: test  
